const admins = [
    {
        id: 1,
        username: "joshandres",
        firstname: "Josh",
        lastname: "Andres",
        email: "JoshA@OurEnglishInc.com",
        role: "Admin",
        active: true,
    },
    {
        id: 2,
        username: "whitneykluttz",
        firstname: "Whitney",
        lastname: "Kluttz",
        email: "WhitneyK@OurEnglishInc.com",
        role: "QA",
        active: true,
    },
    {
        id: 3,
        username: "yitonghu",
        firstname: "Yitong",
        lastname: "Hu",
        email: "YitongH@OurEnglishInc.com",
        role: "Guest",
        active: true,
    },
    {
        id: 4,
        username: "johanserrato",
        firstname: "Johan",
        lastname: "Serrato",
        email: "jromero@OurEnglish.ai",
        role: "Guest",
        active: false,
    },
]